### LOGIN (obter token)
POST http://localhost:8080/login
Content-Type: application/json

{
    "login": "luan_venancio",
    "senha": "Unileste"
}

### LISTAR TODAS AS PESSOAS (GET)
GET http://localhost:8080/pessoas
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6MSwiaWF0IjoxNzQ0MDQ2NDE5LCJleHAiOjE3NDQwODk2MTl9.9PoK3cyAxBs9l3u1zpcnE2dlXEi9MEHQPTz3sT57_Zs

### BUSCAR PESSOA POR ID (GET)
GET http://localhost:8080/pessoas/1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6MSwiaWF0IjoxNzQ0MDQ2NDE5LCJleHAiOjE3NDQwODk2MTl9.9PoK3cyAxBs9l3u1zpcnE2dlXEi9MEHQPTz3sT57_Zs

### CRIAR PESSOA (POST)
POST http://localhost:8080/pessoas
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6MSwiaWF0IjoxNzQ0MDQ2NDE5LCJleHAiOjE3NDQwODk2MTl9.9PoK3cyAxBs9l3u1zpcnE2dlXEi9MEHQPTz3sT57_Zs

{
    "nome": "Maria Silva",
    "celular": "31999999999",
    "cpfCnpj": "12345678901",
    "rua": "Rua das Flores",
    "numero": "100",
    "bairro": "Centro",
    "cidade": "Belo Horizonte",
    "uf": "MG"
}

### ATUALIZAR PESSOA (PUT)
PUT http://localhost:8080/pessoas/1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6MSwiaWF0IjoxNzQ0MDQ2NDE5LCJleHAiOjE3NDQwODk2MTl9.9PoK3cyAxBs9l3u1zpcnE2dlXEi9MEHQPTz3sT57_Zs

{
    "nome": "Maria Silva Santos",
    "celular": "31988888888",
    "cpfCnpj": "12345678901",
    "rua": "Rua das Flores",
    "numero": "100",
    "bairro": "Centro",
    "cidade": "Belo Horizonte",
    "uf": "MG"
}

### EXCLUIR PESSOA (DELETE)
DELETE http://localhost:8080/pessoas/1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6MSwiaWF0IjoxNzQ0MDQ2NDE5LCJleHAiOjE3NDQwODk2MTl9.9PoK3cyAxBs9l3u1zpcnE2dlXEi9MEHQPTz3sT57_Zs