### Testando a rota /cad_usuario para cadastro de usuário
POST http://localhost:8080/cad_usuario
Content-Type: application/json

{
    "nome": "João Silva",
    "login": "joao.silva",
    "senha": "senha123",
    "nivelAcesso": 1
}
