### Acessar a rota protegida de usuários
GET http://localhost:8080/usuarios
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6MSwiaWF0IjoxNzQxOTcwOTkyLCJleHAiOjE3NDE5NzQ1OTJ9.KWN_3r8lIbzGoucbtD-y9I1z5cLKiIOQNWiqRtZU-d0
