POST http://localhost:8080/usuarios
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6MSwiaWF0IjoxNzQzODg4Mjg2LCJleHAiOjE3NDM4OTE4ODZ9.I2Pvz0I2YV5ggOdtu4AEIRg8poZ6AY4UOJG0H5lj_Xs

{
  "nome": "João Silva",
  "login": "joao.silva",
  "senha": "123456",
  "nivelAcesso": "1"
}

